<?php

return [
    'bank_name' => [
        'Vietcombank',
        'Vietinbank',
        'BIDV',
        'Agribank',
        'VPBank',
        'Sacombank',
        'ACB',
        'HSBC',
        'DongA Bank',
        'TPBank',
        'EximBank',
        'VIB',
        'SHB',
        'Shinhan Bank',
        'Vietbank',
        'PG Bank',
        'SCB',
        'MSB',
        'ABBank',
        'MBBank',
        'LienVietPostBank',
        'SeABank',
        'Standard Chartered',
        'PVcomBank',
        'UOB',
        'First Bank',
        'Woori Bank',
        'Nam A Bank',
        'Saigonbank',
        'Bac A Bank',
        'HDBank',
        'Viet Capital Bank',
        'VietABank',
        'GPBank',
        'NCB',
        'KienLong Bank',
        'OceanBank',
        'CBBank',
        'BAOVIET Bank',
        'VBSP',
        'VDB',
        'Public Bank Việt Nam',
        'Indovina Bank',
        'VRB',
        'HongLeong Bank'
    ],
    'branch' => [
        'Tp HCM',
        'Hà Nội',
        'An Giang',
        'Bà Rịa – Vũng Tàu',
        'Bạc Liêu',
        'Bắc Giang',
        'Bắc Kạn',
        'Bắc Ninh',
        'Bến Tre',
        'Bình Dương',
        'Bình Định',
        'Bình Phước',
        'Bình Thuận',
        'Cà Mau',
        'Cao Bằng',
        'Cần Thơ',
        'Đà Nẵng',
        'Đắk Lắk',
        'Đắk Nông',
        'Điện Biên',
        'Đồng Nai',
        'Đồng Tháp',
        'Gia Lai',
        'Hà Giang',
        'Hà Nam',
        'Hà Tĩnh',
        'Hải Dương',
        'Hải Phòng',
        'Hậu Giang',
        'Hòa Bình',
        'Hưng Yên',
        'Khánh Hòa',
        'Kiên Giang',
        'Kon Tum',
        'Lai Châu',
        'Lạng Sơn',
        'Lào Cai',
        'Lâm Đồng',
        'Long An',
        'Nam Định',
        'Nghệ An',
        'Ninh Bình',
        'Ninh Thuận',
        'Phú Thọ',
        'Phú Yên',
        'Quảng Bình',
        'Quảng Nam',
        'Quảng Ngãi',
        'Quảng Ninh',
        'Quảng Trị',
        'Sóc Trăng',
        'Sơn La',
        'Tây Ninh',
        'Thái Bình',
        'Thái Nguyên',
        'Thanh Hóa',
        'Thừa Thiên Huế',
        'Tiền Giang',
        'Trà Vinh',
        'Tuyên Quang',
        'Vĩnh Long',
        'Vĩnh Phúc',
        'Yên Bái',
    ],
    'vi_dien_tu' => [
        'MoMo',
        'Viettel Money',
        'ZaloPay',
        'VTC Pay',
        'Payoo',
        'ShopeePay',
        'VNPay',
        'Moca',
        'Vimo',
        'VinID',
        'BankPlus',
        'Payoneer',
        'Ngân Lượng',
        'Ví Việt'
    ]
];
